=== Jeroo/TrabajoFinalXML/web/pagina vivero XML/paginas/contacto.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema 
           version="1.0"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
            
    <xsd:element name="paginaContactos">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="imagenes">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="imagenCabecera" minOccurs="0" maxOccurs="1">
                                <xsd:complexType>                                   
                                    <xsd:attribute name="imagenUri" use="required" type="xsd:string"/>                                   
                                </xsd:complexType>                 
                            </xsd:element>
                            <xsd:element name="imagenCarruse" minOccurs="0" maxOccurs="1">
                                <xsd:complexType>                                   
                                    <xsd:attribute name="imagenUri" use="required" type="xsd:string"/>                                   
                                </xsd:complexType>                 
                            </xsd:element>                           
                        </xsd:sequence>                                 
                    </xsd:complexType>                 
                </xsd:element>
                <xsd:element name="dirección" type="modelDireccion" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="teléfono" type="modeloTelefonoFax" minOccurs="1" maxOccurs="unbounded"/>
                <xsd:element name="fax" type="modeloTelefonoFax" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element name="correosElectrónicos" type="modeloCorreosElectronicos" minOccurs="1" maxOccurs="unbounded"/>
                <xsd:element name="formulariosContactos" type="modelFormulariosContactos" minOccurs="0" maxOccurs="1"/>
                <xsd:element name="iframeUrl" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>                                   
                        <xsd:attribute name="url" use="required" type="xsd:string"/>                                   
                    </xsd:complexType>                 
                </xsd:element>               
            </xsd:sequence>
        </xsd:complexType>
        
    </xsd:element>
    
     <xsd:complexType name="modeloCorreosElectronicos">
         <xsd:sequence>
             <xsd:element name="correoElectronicoCentroPagina" type="modeloCorreoElectronico" minOccurs="0" maxOccurs="unbounded"/>
             <xsd:element name="correoElectronicoPiePagina" type="modeloCorreoElectronico" minOccurs="1" maxOccurs="unbounded"/>
         </xsd:sequence>
    </xsd:complexType>
    
     <xsd:complexType name="modelDireccion">
         <xsd:sequence>
             <xsd:element name="nombreLugar" type="xsd:string" minOccurs="0" maxOccurs="1"/>             
             <xsd:element name="calle">
                 <xsd:complexType>
                     <xsd:sequence>
                          <xsd:element name="nombre" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                          <xsd:element name="número" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                          <xsd:element name="referencia" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                          <xsd:element name="referencia2" type="xsd:string" minOccurs="0" maxOccurs="1"/>                   
                     </xsd:sequence>                     
                 </xsd:complexType>                 
             </xsd:element>
             <xsd:element name="sector" type="xsd:string" minOccurs="0" maxOccurs="1"/>
             <xsd:element name="localidad" type="xsd:string" minOccurs="1" maxOccurs="1"/>
             <xsd:element name="códigoPostal" type="xsd:string" minOccurs="0" maxOccurs="1"/>
             <xsd:element name="país" type="xsd:string" minOccurs="1" maxOccurs="1"/>
         </xsd:sequence>
    </xsd:complexType>
    
     <xsd:complexType name="modelFormulariosContactos">
         <xsd:sequence>
             <xsd:element name="contacto" type="modeloContacto" minOccurs="0" maxOccurs="unbounded"/>
         </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="modeloContacto">
         <xsd:sequence>
             <xsd:element name="nombre" type="xsd:string" minOccurs="0" maxOccurs="1"/>
             <xsd:element name="correoElectrónico" type="xsd:string" minOccurs="0" maxOccurs="1"/>
             <xsd:element name="asunto" type="xsd:string" minOccurs="0" maxOccurs="1"/>
             <xsd:element name="mensaje" type="xsd:string" minOccurs="0" maxOccurs="1"/>
             <xsd:element name="condicionesGenerales" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
         </xsd:sequence>
    </xsd:complexType>
    
    <xsd:simpleType name="modeloTelefonoFax">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\s*([+][0-9]{2}\s*[0-9]{2}\s*[0-9]{3}\s*[0-9]{2}\s*[0-9]{2})\s*"/>
        </xsd:restriction>
    </xsd:simpleType>
    
     <xsd:simpleType name="modeloCorreoElectronico">
        <xsd:restriction base="xsd:string">
               <xsd:pattern value="[^@]+@[^\.]+\..+\s*"/> 
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== Jeroo/TrabajoFinalXML/web/pagina vivero XML/paginas/contacto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet  href="contacto.xsl" type="text/xsl"?>

<paginaContactos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="contacto.xsd"> 
    <imagenes>
        <imagenCabecera imagenUri="../imagenes/Cabecera.jpg"/> 
        <imagenCarruse imagenUri="../imagenes/Carrusel4.jpg"/>       
    </imagenes> 
    <dirección>
      <nombreLugar>
        Centro de jardinería y exposición
      </nombreLugar>
      <calle>
          <nombre>Carretera de Barcelona</nombre>
          <número>Km. 16,500</número>
          <referencia>Autovía A2 Km.16 sentido Madrid</referencia>
          <referencia2>Autovía A2 Km. 16,500 sentido Madrid</referencia2>
      </calle>
      <sector>
          San Fernando de Henares
      </sector>
      <localidad>
          Madrid
      </localidad>      
      <códigoPostal>
          28830
      </códigoPostal>
      <país>
          España
      </país>
    </dirección>  
    <teléfono>
        +34 91 555 55 55
    </teléfono>
    <fax>
     +34 91 555 55 55 
    </fax> 
    <correosElectrónicos>
        <correoElectronicoCentroPagina>
            info@viverospena.com
        </correoElectronicoCentroPagina>
         <correoElectronicoPiePagina>
            info@viveroUAH.com
        </correoElectronicoPiePagina>     
    </correosElectrónicos>   
    <formulariosContactos>
        <contacto>
            <nombre> 
               Salvador
           </nombre> 
           <correoElectrónico> 
               scuevas@outlook.com
           </correoElectrónico> 
           <asunto> 
               Mensaje de prueba
           </asunto> 
            <mensaje> 
               cuerpo del mensaje de prueba
           </mensaje> 
           <condicionesGenerales> 
               true
           </condicionesGenerales>
        </contacto>              
     </formulariosContactos> 
  
     <iframeUrl url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3033.476855108628!2d-3.3451889999999795!3d40.50895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd424bfc76f087f1%3A0xced3a1e98249a30f!2sUAH+Campus+Cient%C3%ADfico-Tecnol%C3%B3gico+(Externo)!5e0!3m2!1ses!2ses!4v1428406958641"/>
    
</paginaContactos>
